spin_manifest_version = 2

[application]
authors = ["roman.chuvilev <roman.chuvilev@arkadium.com>"]
description = ""
name = "openai-request"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "openai-request"

[component.openai-request]
source = "target/openai-request.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://api.openai.com"]

[component.openai-request.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
