spin_manifest_version = 2

[application]
authors = ["roman.chuvilev <roman.chuvilev@arkadium.com>"]
description = ""
name = "openai-api-key"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "openai-api-key"

[component.openai-api-key]
source = "target/openai-api-key.wasm"
exclude_files = ["**/node_modules"]
[component.openai-api-key.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]